source 'https://rubygems.org'

ruby '2.1.6'

gem 'sinatra', require: 'sinatra/base'
gem 'sinatra-contrib'
gem 'rack-standards'
# gem 'rack-flash'
gem 'sinatra-flash', require: 'sinatra/flash'
gem 'unicorn'
gem 'erubis'
gem 'i18n'
gem 'rake'
gem 'json'
gem 'dotenv'
gem 'builder'

# DB
gem 'mongo'
gem 'mongoid', '3.1.6'
gem 'mongoid_search'
gem 'bson_ext'

# Authentication
gem 'omniauth-google-oauth2'

# Assets
gem 'carrierwave-mongoid', require: 'carrierwave/mongoid'
gem 'mongoid-grid_fs', github: 'ahoward/mongoid-grid_fs'
gem 'sprockets'
gem 'stylus'
gem 'uglifier'
gem 'yui-compressor'
gem 'closure-compiler'
gem 'eco'
gem 'pony'
gem 'parallel'
gem 'uuid'
gem 'awesome_print'
gem 'colored'
gem 'nokogiri'
gem 'rest-client'
gem 'delayed_job'
gem 'delayed_job_mongoid'
gem 'mini_magick'
gem 'prawn', '~> 1.2.1'
gem 'prawn-table', '~> 0.1.0'
gem 'twilio-ruby'
gem 'multi_json'
gem 'fog'
gem 'sshkey'
gem 'rmagick' # rmagick requires installing ghostscript, imagemagick, imagemagick-devel
gem 'slack-ruby-client'
gem 'dalli'
gem 'memcachier'
gem 'daemons'
# gem 'celluloid-io' # for slack-real-time client concurrency