source 'https://rubygems.org'

ruby "2.0.0"
gem 'sinatra'
gem 'sinatra-contrib'
gem 'rack-flash'
gem 'sinatra-flash'
gem 'pony'
gem 'mongo'
gem 'mongoid'
gem 'mongoid_search'
gem 'bson_ext'
gem 'json'
gem 'parallel'
gem 'uuid'
gem 'unicorn'
gem 'awesome_print'
gem 'colored'
gem 'nokogiri'
gem 'rake'
gem 'rest-client'
gem 'delayed_job'
gem 'delayed_job_mongoid'
gem 'mini_magick'
gem 'prawn', '~> 1.2.1'
gem 'prawn-table', '~> 0.1.0'
gem 'twilio-ruby'
gem 'omniauth-google-oauth2'
gem 'multi_json'
gem 'fog'
gem 'sshkey'

gem 'newrelic_rpm'
