class EmailRequestStatus < Struct.new(:settings, :admin, :request, :request_type)
  def perform
    email_body = <<EOBODY
      <p>Hi,</p>
      <p>This update is to let you know that <strong>#{admin}</strong> has <strong>#{request.status}</strong> your request for #{request_type}.</p>
      <p>Request Details:</p>
      <table width="100%" border="0" cellspacing="0" cellpading="0">
        <tr>
          <td align="left" width="20%" valign="top"><strong>Request Made on</strong></td>
          <td align="left" width="20%" valign="top">#{request.created_at}</td>
        <tr>
        <tr>
          <td align="left" width="20%" valign="top"><strong>Request Type:</strong></td>
          <td align="left" width="20%" valign="top">#{request_type}</td>
        <tr>
        <tr>
          <td align="left" width="20%" valign="top"><strong>Approved/Disapproved By:</strong></td>
          <td align="left" width="20%" valign="top">#{admin}</td>
        <tr>
        <tr>
          <td align="left" width="20%" valign="top"><strong>Notes:</strong></td>
          <td align="left" width="20%" valign="top">#{request.notes}</td>
        <tr>
      </table>
      <br/>
      <p><strong>Important</strong>: <font color="red"> Contact #{admin} for more information.</font></p>
      <p><em><strong>Note</strong>: This email is generated by cloudwick sync portal. If you have received this email by error please contact <a href="mailto:admin@cloudwick.com?Subject=Sync%20Misplaced%20Email">admin</a>.</em></p>
      <p>Thanks for using <strong>Cloudwick Sync.</strong></p>
EOBODY
    Pony.mail(
      from: 'Cloudwick Sync' + "<" + settings[:email] + ">",
      to: request.consultant_email,
      cc: settings[:cc],
      subject: "Status of the #{request_type} request you made",
      headers: { 'Content-Type' => 'text/html' },
      body: email_body,
      via: :smtp,
      via_options: {
        address: settings[:smtp_address],
        port: settings[:smtp_port],
        enable_starttls_auto: true,
        user_name: settings[:email],
        password: settings[:password],
        authentication: :plain,
        domain: 'localhost.localdoamin'
      }
    )
  end

  def success
    log "sucessfully sent out status update email to #{request.consultant_email}"
  end

  def error
    log "something went wrong sending status update email out to #{request.consultant_email}"
  end

  def failure
    log "something went wrong sending status update email out"
  end

  # overrides the Delayed::Worker.max_attempts only for this job
  def max_attempts
    5
  end

  def log(text)
    Delayed::Worker.logger.info("#{Time.now.strftime('%FT%T%z')}: [#{self.class.name} (pid: #{Process.pid})] #{text}")
  end
end
