class EmailCertificationNotificationPostDay < Struct.new(:settings, :admin, :request)
  def perform
    email_body = <<EOBODY
      <p>This is a nofication from Sync portal:</p>
      <p><strong>Please update the status of your certification by replying back to <a href="mailto:syncadmin@cloudwick.com?Subject=Certification%20Status%20#{request.short}">syncadmin@cloudwick.com.</a></strong></p>
      <p>Request Details:</p>
      <table width="100%" border="0" cellspacing="0" cellpading="0">
        <tr>
          <td align="left" width="20%" valign="top"><strong>Certification Name:</strong></td>
          <td align="left" width="20%" valign="top">#{request.name}</td>
        <tr>
        <tr>
          <td align="left" width="20%" valign="top"><strong>Certification date requested:</strong></td>
          <td align="left" width="20%" valign="top">#{request.booking_date}</td>
        <tr>
      </table>
      <br/>
      <p><strong>Important</strong>: <font color="red"> Contact #{admin} for more information.</font></p>
      <p><em><strong>Note</strong>: This email is generated by cloudwick sync portal. If you have received this email by error please contact <a href="mailto:admin@cloudwick.com?Subject=Sync%20Misplaced%20Email">admin</a>.</em></p>
      <p>Thanks for using <strong>Cloudwick Sync.</strong></p>
EOBODY
    Pony.mail(
      from: 'Cloudwick Sync' + "<" + settings[:email] + ">",
      to: request.consultant_email,
      cc: settings[:admin_group],
      subject: "Sync: Please update the status of your certification #{request.code}",
      headers: { 'Content-Type' => 'text/html' },
      body: email_body,
      via: :smtp,
      via_options: {
        address: settings[:smtp_address],
        port: settings[:smtp_port],
        enable_starttls_auto: true,
        user_name: settings[:email],
        password: settings[:password],
        authentication: :plain,
        domain: 'localhost.localdoamin'
      }
    )
  end

  def success
    log "sucessfully sent out certification prior day request notification email to #{request.consultant_email}"
  end

  def error
    log "something went wrong sending certification prior day  request notification email out to #{request.consultant_email}"
  end

  def failure
    log "something went wrong sending certification prior day  request notification email out to #{request.consultant_email}"
  end

  # overrides the Delayed::Worker.max_attempts only for this job
  def max_attempts
    5
  end

  def log(text)
    Delayed::Worker.logger.info("#{Time.now.strftime('%FT%T%z')}: [#{self.class.name} (pid: #{Process.pid})] #{text}")
  end
end
