---
#
# Google API
#
google_key: '22486611835-fmoqk1vpoavkdug2iniepeaqpm5tfaqj.apps.googleusercontent.com'
google_secret: 'EBNBSUqdSW2gUyH1Zb1g6o8v'
#
# Mongo
#
mongo_db: job_portal
mongo_host: localhost
mongo_port: 27017
#
# GMail Configuration
#
email: admin@cloudwick.com
cc: jobs@cloudwick.com
admin_group: syncadmin@cloudwick.com
project_notification_group:
  - syncadmin@cloudwick.com
  - mani@cloudwick.com
admin_phone:
  - +12013141533
  - +15594516899
password: balentine380
smtp_address: smtp.gmail.com
smtp_port: 587
#
# Pusher configuration
#
pusher_api_id: '73588'
pusher_key: '6190d80d2c93a25e0192'
pusher.secret: '2e55a93f44287709b37d'
#
# Mail Gun configuration
#
mailgun_api_key: 'key-62-8e5xuuc0b1ojaxobl2n13mkuw4qg2'
mailgun_domain: 'mg.cloudwick.com'
#
# Mail gun vendors
#
mailgun_vendor_email: 'vinay@mg.cloudwick.com'
# forwards replies to specified emails and then also stores them in local mongo
mailgun_vendor_routes_forward:
  - 'jobs@cloudwick.com'
mailgun_vendor_routes_name: 'Email Vendor Campaigning'
#
# Mail gun customers
#
mailgun_customer_email: 'mark.schreiber@mg.cloudwick.com'
mailgun_customer_routes_forward:
  - 'markschreiber@cloudwick.com'
mailgun_customer_routes_name: 'Email Customers Campaigning'
#
# Twilio configuration
#
twilio_account_sid: 'AC23cc89e655af3650bc5f8d25021e9106'
twilio_auth_token: 'c70384f4cc30004651d13eb82e0e967a'
twilio_phone: '+16506145955'
#
# Slack - Cloudwick
#
#slack_domain: 'cloudwick'
#slack_sync_bot_api_token: 'xoxb-13810016625-jExwE2bZe6HGRUAEZPsdRaSt'
#slack_admin_user_api_token: 'xoxp-2187446245-14616018610-14614028692-42bf699309'
#
# Slack - CloudwickLabs
#
slack_domain: 'cloudwicklabs'
slack_sync_bot_api_token: 'xoxb-15105086321-efkUq2h19outpjGpR5N2qcaD'
slack_admin_user_api_token: 'xoxp-15105482151-15105478470-15105606471-948c4c469a'
default_slack_users:
  - ashrith@cloudwick.com
  - admin@cloudwick.com
default_slack_bots:
  - sync
#
# OpenStack Credentials (For CloudServers)
#
openstack_tenant: 'sync'
openstack_api_key: 'Balentine380'
openstack_username: 'sync'
openstack_auth_url: 'http://172.16.4.5:35357/v2.0/tokens'
#
# Portal configuration
#
# public ip address / hostname where the job_portal server is running for
# forwarding the replies and events to
bind_ip: '198.0.218.179'
bind_port: 80
