# http://mongoid.org/en/mongoid/docs/installation.html#configuration
development:
  sessions:
    default:
      database: job_portal
      hosts:
        - localhost:27017
  options:
    raise_not_found_error: false
testing:
  sessions:
    default:
      database: testdb
      hosts:
        - localhost:27017
  options:
    raise_not_found_error: false
production:
  sessions:
    default:
      database: job_portal
      hosts:
        - localhost:27017
  options:
    raise_not_found_error: false