# http://mongoid.org/en/mongoid/docs/installation.html#configuration
development:
  sessions:
    default:
      database: job_portal
      hosts:
        - localhost:27017
# production:
#   sessions:
#     default:
#       uri: <%= ENV['MONGOHQ_URL'] %>
#       options:
#         skip_version_check: true
#         safe: true
