class TrainingAssignment
  include Mongoid::Document

  # name of the assignment - autogenerated 'Assignment #1'
  field :name, type: String
  field :heading, type: String
  field :description, type: String, default: ''
  field :description_link, type: String, default: ''

  belongs_to :training_sub_topic
  has_many :training_assignment_submissions
end
